### ISSUE TITLE
Installation issue, Omeka 2.1.4: This is not a valid plugin

### ISSUE THREAD

**Issue by pyscajor** [dpla-attic/omeka-OpenSeadragon#1]
This looks like a great plugin, with impressive results on http://dp.la/exhibitions/

Unfortunately when I uploaded the plugin (0.3.1) to my Omeka 2.1.4 site, the plugins page warns me that "This is not a valid plugin".

I have the system requirements outlined in the readme - perhaps I'm doing something wrong?

Tom

**Comment by anarchivist** [comment]
The plugin has only been tested on Omeka 2.0; we'll be testing with more recent versions soon.

**Comment by pyscajor** [comment]
OK - thanks. I'll happily test any future versions.

**Comment by anarchivist** [comment]
If you could provide any error logs from Omeka, that would be useful. Thanks!

**Comment by pyscajor** [comment]
Will do.

**Comment by anarchivist** [comment]
I just tested this on a brand new Omeka 2.1.4 installation and confirm that the plugin works. I'm also not seeing the warning that you're seeing. I won't be able to diagnose this without additional info. 

![screen shot 2014-02-18 at 11 49 12 am](https://f.cloud.github.com/assets/73732/2197467/bb26ce1a-98bc-11e3-92c1-0bf8fe32a4b2.png)
![screen shot 2014-02-18 at 11 49 23 am](https://f.cloud.github.com/assets/73732/2197468/bb2740ac-98bc-11e3-9b6c-46f348c74f51.png)

**Comment by pyscajor** [comment]
I just tried again and realised that I lazily didn't rename the OpenSeaDragon directory - my fault entirely. I have renamed the directory `omeka-OpenSeadragon-master` to `OpenSeadragon` and it works wonderfully. 

Sorry about that, and thanks once again for a great plugin!

**Comment by anarchivist** [comment]
Ah, that's something that should probably be covered in the README, then... :)
